config/routes.rb
Rails.application.routes.draw do
  root to: "home#home"
  resources :teams
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flashes.html.erb
<% if notice.present? %>
  <p id="flash-message" data-controller="flash" class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg fixed top-100px" id="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p id="flash-message" data-controller="flash" class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg fixed top-100px" id="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav id="navbar" class=" relative bg-transparent">
  <div id="navbar-container" class="container mx-auto flex flex-row justify-between items-center h-16">
    <div id="navbar-left" class=" flex items-center" >
      <%= link_to "Home", root_path, id: "navbar-item", class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2 " %>
    </div>
    <div id="navbar-right" class="">
      <ul id="navbar-nav" class="flex flex-row space-x-4 items-center">
        <% if current_user %>
          <li id="nav-item" >
            <%= link_to "Teams", teams_path, id: "nav-link", class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2" %>
          </li>
          <li id="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path, id: "nav-link", class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2" %>
          </li>
          <li id="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2 mx-2" %>
          </li>
        <% else %>
          <li id="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, id: "nav-link", class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2" %>
          </li>
          <li id="nav-item">
            <%= link_to "Sign In", new_user_session_path, data: { turbo_frame: 'modal' }, class: "nav-link", class: "text-3xl text-white text-shadow shadow-blue-800 hover:bg-slate-500 hover:bg-opacity-40 rounded-2xl px-3 py-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class=" w-full flex justify-center z-10">
    <%= render 'layouts/flashes' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tfp Practise" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <main class="container mx-auto mt-20 px-5 flex flex-col">
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="turbo-modal" id="login-modal-bg" class=" fixed inset-0 bg-black bg-opacity-25 flex items-center justify-center w-full">
    <div id="login-modal-container" class="bg-white p-6 rounded-3xl shadow-lg">
      <div id="login-header" class=" flex flex-row justify-between">
        <h2 class="text-5xl">Log in</h2>
        <button data-action="turbo-modal#hideModal" type="button" class=" h-6 w-6 bg-red-500 rounded-full border-2 border-red-500 justify-center items-center flex" >
          <div class="">&#x2715;</div>
        </button>
      </div>
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "current-password" %>
        </div>
        <% if devise_mapping.rememberable? %>
          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        <% end %>
        <div class="actions">
          <%= f.submit "Log in" %>
        </div>
      <% end %>
      <%= render "devise/shared/links" %>
    </div>
  </div>
<% end %>